# Generated by Django 3.2.6 on 2021-08-15 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.PositiveIntegerField(default=0)),
                ('car_seats', models.PositiveIntegerField(default=0)),
                ('car_color', models.CharField(max_length=50)),
                ('car_vin', models.CharField(max_length=17)),
                ('car_curr_mileage', models.PositiveIntegerField(default=0)),
                ('car_service_interval', models.PositiveIntegerField(default=0)),
                ('car_next_service', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
