# Generated by Django 3.2.6 on 2021-08-16 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_make', models.CharField(max_length=50)),
                ('truck_model', models.CharField(max_length=50)),
                ('truck_year', models.PositiveIntegerField(default=0)),
                ('truck_seats', models.PositiveIntegerField(default=0)),
                ('truck_bed_length', models.PositiveIntegerField(default=0)),
                ('truck_color', models.CharField(max_length=50)),
                ('truck_vin', models.CharField(max_length=17)),
                ('truck_curr_mileage', models.PositiveIntegerField(default=0)),
                ('truck_service_interval', models.PositiveIntegerField(default=0)),
                ('truck_next_service', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
