# Generated by Django 3.2.6 on 2021-08-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_garage', '0003_boat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
