from django.urls import path, include
from . import views
from rest_framework import routers

# Router will generate the URLS for our models
router = routers.DefaultRouter()
router.register('vehicle_garage/cars', views.CarView)
router.register('vehicle_garage/trucks', views.TruckView)
router.register('vehicle_garage/boats', views.BoatView)

# Holds the actual URLs generated by the router
urlpatterns = [
    path('', include(router.urls))
]